"""add tournament_templates

Revision ID: 942ef0c78cdc
Revises: 0001_initial_users
Create Date: 2026-06-04 00:22:52.719980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '942ef0c78cdc'
down_revision: Union[str, None] = '0001_initial_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tournament_templates_id'), 'tournament_templates', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.drop_index(op.f('ix_tournament_templates_id'), table_name='tournament_templates')
    op.drop_table('tournament_templates')
    # ### end Alembic commands ###
